input_data_path: "C:/Users/Mikhail Korotkov/PycharmProjects/liahimratman/ml_project/data/heart.csv"
output_model_path: "C:/Users/Mikhail Korotkov/PycharmProjects/liahimratman/ml_project/models/model.pkl"
metric_path: "C:/Users/Mikhail Korotkov/PycharmProjects/liahimratman/ml_project/models/metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 4
train_params:
  model_type: "LogisticRegression"
  random_state: 100
feature_params:
  numerical_features:
    - "age"
    - "cp"
    - "trestbps"
    - "chol"
    - "fbs"
    - "restecg"
    - "thalach"
    - "exang"
    - "oldpeak"
    - "slope"
    - "ca"
    - "thal"
  categorical_features:
    - "sex"
  target_col: "target"