input_data_path: ml_project/data/heart.csv
output_model_path: ml_project/models/model.pkl
output_config_path: ml_project/configs/evaluation_config.yaml
metric_path: ml_project/models/metrics.json
splitting_params:
  val_size: 0.2
  random_state: 4
train_params:
  model_type: "LogisticRegression"
  max_iter: 1000
  random_state: 4
feature_params:
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "fbs"
    - "restecg"
    - "thalach"
    - "exang"
    - "oldpeak"
    - "slope"
    - "ca"
    - "thal"
  categorical_features:
    - "cp"
    - "sex"
  target_col: "target"