name: Pytest

on:
  push:
    branches: [ homework1 ]
  pull_request:
    branches: [ homework1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Running pytest
      run: |
        cd homework1
        pytest tests.py
