name: Pylint

on:
  push:
    branches: [ homework1 ]
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint **/*.py
